- name: db cofiguration
  hosts: localhost
  vars:
    login_host: db.sireesha.online
  vars_prompt:
    - name: mysql_root_password
      prompt: enter the password
      private: no
  become: yes
  tasks:
    - name: install mysql-server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: mysql service setup
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: install python mysql dependency
      ansible.builtin.pip:
        name:
        - pymysql
        - cryptography



    - name: db password setup
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{mysql_root_password}}"
        login_host: "{{login_host}}"
        filter: version
      ignore_errors: yes
      register: mysql_connection_output

    - name: print the output
      ansible.builtin.debug:
        msg: "{{mysql_connection_output}}"

    - name: setup root password
      ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
      when: mysql_connection_output.failed is true


