- name: configure db server
  hosts: db
  become: yes
  vars:
    login_host: db.sireesha.online
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter mysql root password
    private: no
  tasks:
    - name: install the nginx server
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: start the mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: install mysql dependencies
      ansible.builtin.pip:
        name:
          - pymysql
          - cryptography
      executable: 3.9

    - name: check db connection
      community.mysql.mysql_info:
         login_user: root
         login_password: "{{mysql_root_password}}"
         login_host: "{{login_host}}"
         filter: version
      ignore_errors: yes
      register: mysql_connection_output


    - name: print the output information
      ansible.builtin.debug:
        msg: "{{mysql_connection_output}}"

    - name: setup root password
      ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
      when: mysql_connection_output.failed is true


